name: travo_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.8
  connectivity_plus: ^5.0.2
  country_picker: ^2.0.25
  dartz: ^0.10.1
  device_preview: ^1.1.0
  easy_dialog: ^1.1.1
  equatable: ^2.0.5
  firebase_app_check: ^0.2.1+17
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  go_router: ^13.2.1
  hydrated_bloc: ^9.1.5
  image_picker:
    path: package/image_picker
  import_sorter: ^4.6.0 
  intl: ^0.18.0
  logger: ^2.2.0
  lottie: ^3.1.0
  path_provider: ^2.1.2
  uuid: ^4.3.3
  wechat_assets_picker: ^9.0.3

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/animation/
  fonts:
    - family: TravoAppIcon
      fonts:
        - asset: assets/icons/TravoAppIcon.ttf
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: Helvetica
      fonts:
        - asset: assets/fonts/Helvetica-Light.ttf
          weight: 300
        - asset: assets/fonts/Helvetica.ttf
          weight: 400
        - asset: assets/fonts/Helvetica-Bold.ttf
          weight: 700


