  
  //TODO: tạm thời xử lý chọn quốc gia ra số đã
  //Còn đa vùng để sau
  Map<String, String> countryCode= {
    'Vietnam': '+84',
    //'USA': ['+1', '+1 684', '+1 671'],
    'UK': '+44',
    'Argentina': '+54',
    'Australia': '+61',
    'Brazil': '+55',
    //'Canada': ['+1', '+1 684', '+1 671'],
    'China': '+86',
    'France': '+33',
    'Germany': '+49',
    'India': '+91',
    'Indonesia': '+62',
    'Japan': '+81',
    'Mexico': '+52',
    'Russia': '+7',
    'South Korea': '+82',
    'Spain': '+34',
    'Thailand': '+66',
    'Turkey': '+90',
    'Ukraine': '+380',
    'South Africa': '+27',
    'Italy': '+39',
    'Algeria': '+213',
    'Angola': '+244',
    'Bangladesh': '+880',
    'Belgium': '+32',
    'Chile': '+56',
    'Colombia': '+57',
    'Czech Republic': '+420',
    'Denmark': '+45',
    'Egypt': '+20',
    'Finland': '+358',
    'Greece': '+30',
    'Hungary': '+36',
    'Iran': '+98',
    'Iraq': '+964',
    'Ireland': '+353',
    'Israel': '+972',
    'Kenya': '+254',
    'Malaysia': '+60',
    'Netherlands': '+31',
    'New Zealand': '+64',
    'Nigeria': '+234',
    'Norway': '+47',
    'Pakistan': '+92',
    'Peru': '+51',
    'Philippines': '+63',
    'Poland': '+48',
    'Portugal': '+351',
    'Romania': '+40',
    'Saudi Arabia': '+966',
    'Singapore': '+65',
    'Sweden': '+46',
    'Switzerland': '+41',
    'Taiwan': '+886',
    'Tanzania': '+255',
    'Zimbabwe': '+263',
  };
